from environs import Env

env = Env()
env.read_env()

TOKEN = env.str("TOKEN")
SECRET_KEY = env.str("SECRET_KEY")
DEBUG = env.bool("DEBUG")
ADMINS = env.list("ADMINS")
GROUP_ID = env.str("GROUP_ID")
LOG_GROUP_ID=env.str("LOG_GROUP_ID")
BOT = env.str("BOT") # bot username
# PAYME_ID = env.str("PAYME_ID")
# PAYME_KEY = env.str("PAYME_KEY")
# TOTAL_AMOUNT = env.int("TOTAL_AMOUNT")
# ADMIN_LINK = env.str("ADMIN_LINK")

#media storage
CLOUDFLARE_R2_BUCKET = env.str("CLOUDFLARE_R2_BUCKET")
CLOUDFLARE_R2_BUCKET_ENDPOINT = env.str("CLOUDFLARE_R2_BUCKET_ENDPOINT")
CLOUDFLARE_R2_ACCESS_KEY = env.str("CLOUDFLARE_R2_ACCESS_KEY")
CLOUDFLARE_R2_SECRET_KEY = env.str("CLOUDFLARE_R2_SECRET_KEY")
CLOUDFLARE_R2_PUBLIC_URL = env.str("CLOUDFLARE_R2_PUBLIC_URL")
CUSTOM_DOMAIN = env.str("CUSTOM_DOMAIN")


REDIS = env.str('REDIS')