# Generated by Django 5.2.6 on 2025-11-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='duration',
            field=models.CharField(blank=True, help_text="Enter duration like '2h 30m', '1h', or '45m'", max_length=64, null=True),
        ),
    ]
