# Generated by Django 5.2.6 on 2025-11-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_movies_actors_movies_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='actors',
        ),
        migrations.AddField(
            model_name='movies',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.movieactors'),
        ),
    ]
