# Generated by Django 5.2.6 on 2025-11-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_movies_actors_movies_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='actors',
        ),
        migrations.DeleteModel(
            name='MovieActors',
        ),
        migrations.AddField(
            model_name='movies',
            name='actors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
