# Generated by Django 5.2.6 on 2025-11-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_movies_actors_delete_movieactors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerChannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('channel_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Partner Channel',
                'verbose_name_plural': 'Partner Channels',
            },
        ),
    ]
