# Generated by Django 5.2.6 on 2025-11-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_partnerchannels'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerchannels',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
