#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python3 manage.py makemigrations

python3 manage.py migrate

 python3 manage.py collectstatic --noinput

# Run Gunicorn server using WSGI
exec gunicorn config.wsgi:application --bind 0.0.0.0:8000 --timeout 120

# Run Uvicorn server using ASGI
# exec uvicorn core.asgi:application --host 0.0.0.0 --port 8000 --reload
